export const ProfessorList = [
  {
    name: "이광수",
    Position: "교수",
    Phone: "02)710-9429",
    Email: "rhee@sm.ac.kr",
    Website: "http://cs.sookmyung.ac.kr/~rhee/",
    Field: "정보 보호",
    Location: "새힘관 103호",
  },
  {
    name: "김주균",
    Position: "교수",
    Phone: "02)710-9430",
    Email: "jgkim@sm.ac.k",
    Website: "http://cs.sookmyung.ac.kr/~jgkim/",
    Field: "운영체제, 컴퓨터구조",
    Location: "새힘관 412",
  },
  {
    name: "최종원",
    Position: "교수",
    Phone: "02)710-9445",
    Email: "choejn@sm.ac.kr",
    Website: "-",
    Field: "컴퓨터네트워크",
    Location: "새힘관 411",
  },
  {
    name: "창병모",
    Position: "교수",
    Phone: "02)710-9378",
    Email: "chang@sm.ac.kr",
    Website: "http://cs.sookmyung.ac.kr/~chang",
    Field: "프로그래밍 언어, IoT 소프트웨어",
    Location: "새힘관 410",
  },
  {
    name: "최영우",
    Position: "교수",
    Phone: "02)710-9763",
    Email: "ywchoi@sookmyung.ac.kr",
    Website: "-",
    Field: "인공지능, 영상처리, 머신러닝",
    Location: "새힘관 409",
  },
  {
    name: "심준호",
    Position: "교수",
    Phone: "02)710-9643",
    Email: "jshim@sm.ac.kr",
    Website: "http://cs.sookmyung.ac.kr/~jshim",
    Field: "데이터베이스, 빅데이터",
    Location: "새힘관 407",
  },
  {
    name: "김윤희",
    Position: "교수",
    Phone: "02)710-9664",
    Email: "yulan@sm.ac.kr",
    Website: "http://cs.sookmyung.ac.kr/~yulan/",
    Field: "분산 시스템",
    Location: "새힘관 402",
  },
  {
    name: "유석종",
    Position: "교수",
    Phone: "02)710-9831",
    Email: "sjyu@sm.ac.kr",
    Website: "https://sites.google.com/view/cglab/",
    Field: "정보시각화, 머신러닝",
    Location: "새힘관 414",
  },
  {
    name: "이기용",
    Position: "교수",
    Phone: "02)2077-7583",
    Email: "kiyonglee@sm.ac.kr",
    Website: "http://cs.sookmyung.ac.kr/~kylee",
    Field: "데이터베이스, 데이터마이닝, 빅데이터",
    Location: "새힘관 406",
  },
  {
    name: "김윤진",
    Position: "교수",
    Phone: "02)2077-7584",
    Email: "ykim@sm.ac.kr",
    Website: "http://esl.sookmyung.ac.kr/",
    Field: "VLSI/System-on-Chip 설계, 임베디드 시스템",
    Location: "새힘관 403",
  },
  {
    name: "박영훈",
    Position: "교수",
    Phone: "02)2077-7326",
    Email: "yh.park@sm.ac.kr",
    Website: "http://whistle.sookmyung.ac.kr/",
    Field: "정보 보안, 최적화",
    Location: "새힘관 101",
  },
  {
    name: "채희준",
    Position: "교수",
    Phone: "02)2077-7414",
    Email: "heechae@sm.ac.kr",
    Website: "https://cbi-bioinfo.github.io/",
    Field: "데이터사이언스, 바이오/헬스, 빅데이터마이닝",
    Location: "새힘관 104",
  },
  {
    name: "정영주",
    Position: "교수",
    Phone: "02)2077-7611",
    Email: "yjeong@sm.ac.kr",
    Website: "http://sites.google.com/site/youngjujeongcv/",
    Field: "3D 디스플레이 설계 및 렌더링, 가상현실/증강현실",
    Location: "새힘관 505",
  },
  {
    name: "박숙영",
    Position: "초빙교수",
    Phone: "blue@sookmyung.ac.kr",
    Email: "-",
    Website: "-",
    Field: "무선 네트워크 통신",
    Location: "-",
  },
  {
    name: "이현자",
    Position: "초빙교수",
    Phone: "-",
    Email: "hyunjalee@sookmyung.ac.kr",
    Website: "-",
    Field: "데이터베이스, 빅데이터",
    Location: "-",
  },
  {
    name: "박재년",
    Position: "명예교수",
    Phone: "-",
    Email: "jnpark@sookmyung.ac.kr",
    Website: "http://cs.sookmyung.ac.kr/~parkjn/",
    Field: "소프트웨어 공학",
    Location: "-",
  },
  {
    name: "문봉희",
    Position: "명예교수",
    Phone: "-",
    Email: "moon@sm.ac.kr",
    Website: "http://bud.sookmyung.ac.kr/",
    Field: "컴퓨터 구조",
    Location: "-",
  },
];
